### ISSUE TITLE
Confusion about message and data flows

### ISSUE THREAD

**Issue by briantopping** [hseeberger/reactive-flows#6]
Great stuff! Thanks for your work on this and the inspiration it's generated.

As a point of constructive feedback, it's difficult to trace all the different data flow mechanisms in play. The domain is obviously of messages contained by flows and there are commands and events that are propagated by PubSub. Is CRDT replication necessary if events are being broadcast to the cluster?

It also seems that every node is going to persist all of the data whereas cluster sharding will allow distributed actors to avoid this. 

Maybe the reason there's not much documentation is these ideas are in flux and I'd imagine you don't get much time to sleep anyway. So just letting you know people are thinking about what you're doing. It's already a really awesome template for people willing to dig and could become "Scala's AppFuse". Cheers!

**Comment by hseeberger** [comment]
Thanks a lot for the feedback! I should definitely document the design including the motivations. So far I have mainly used Reactive Flows for learning and demonstrating (at conferences) all the contained concepts. But I agree that some documentation would definitely help many others (who can't attend my talks). Will do that eventually ;-)

Here's a compressed version, targeted at your questions:

CRDT is used to propagate the information about the names/labels of the flows through the system as opposed to the flows (with messages) themselves. CRDT are definitely needed in order to make sure this information is (eventually) consistent throughout the cluster – just imagine an event published by pub-sub gets lost ...

Pub-sub, on the other hand, is effectively used to stream events (about flow and message changes) to clients. As this communication is inherently unreliable and consistency is not needed (nothing really bad happens is a client doesn't see a new flow or message).

I don't understand your persistence related question: Of course each Flow actor – regardless on which node it resides – persists its state (messages). That's because of sharding: Once sharding decides – for whatever reason – to relocate a shard, Flow actors are recreated. In order to maintain their state Akka persistence is a must. In other words: While Cluster Sharding deals with sharding, i.e. moving actors through the cluster, it does not deal with their state. Therefore it's absolutely essential to use Akka Persistence, if you have stageful actors. BTW, this is even mentioned somewhere in the documentation about Akka Cluster Sharding.

**Comment by briantopping** [comment]
Ah great, thanks Heiko! I'm glad the question wasn't too painful!  :)

I think I can make progress with this info. Mostly because it fills in a lot of gaps, some I didn't even know I had, partly so I can be confident that I'm not looking at code "one commit short of a full hand". It's always a little exhausting to get to the end of a marathon code ingestion and realize that it's not in a completely stable state. So this is everything I need for now.

I wonder what could be done to grow the code so it's still minimal and presentable for your mentoring needs but also moving forward so interested parties can get a running start. I'm really enjoying the packaging in https://github.com/jgordijn/cqrs_template, and while I have mostly self-deprogrammed from "OSGi all the things" mode, it seems to be perfect for the way the cqrs_template packaging is set up. I'm definitely not advocating in that direction, but if you were like "OMG yah let's do it", I could put some PRs together. 

WDYT?

**Comment by hseeberger** [comment]
Brian,

I'm glad you like the demo. Currently I have no plans to turn this into something like a template. On the contrary: If you look at the commit history, you will see, that each commit corresponds to a certain step in the development of the demo from scratch. This means that one can't simply add commits.

Feel free to clone or otherwise use this code to create a template.

**Comment by briantopping** [comment]
Ah perfect, thanks! :)
