### ISSUE TITLE
How to test sse endpoint using external client?

### ISSUE THREAD

**Issue by pawelkaczor** [hseeberger/reactive-flows#9]
I tried to run following node app:

~~~
var EventSource = require('eventsource');

var es = new EventSource('http://127.0.0.1:9001/message-events');

es.onmessage = function(e) {
  console.log(e);
};
es.onerror = function() {
  console.log('ERROR!');
};

~~~

and could't see any messages on the console.

See: https://www.npmjs.com/package/eventsource

**Comment by hseeberger** [comment]
Message events – like all the events in Reactive Flows – carry an event type, as you can see here: https://github.com/hseeberger/reactive-flows/blob/master/src/main/scala/de/heikoseeberger/reactiveflows/ServerSentEventProtocol.scala#L38

So instead of `es.onmessage` which you must register a handler for "added" event types, like in the JS client: https://github.com/hseeberger/reactive-flows/blob/master/src/main/resources/web/js/controllers.js#L90

**Comment by pawelkaczor** [comment]
Thanks!
